language: java
script: mvn clean install
before_deploy:
- mvn help:evaluate -N -Dexpression=project.version|grep -v '\['
- export project_version=$(mvn help:evaluate -N -Dexpression=project.version|grep
  -v '\[')
deploy:
  provider: releases
  api_key:
    secure: "ejN1fgJ0ddlxfY4qYig+pPLh8M7J8b2in6Id5W/IBYGjyGS5EQAsfFczUmQmYxuUgW7WkuEeMLAzFL9xTX4Ne4HGvicAjfOnlLbD103+zp5I1HiKSL4AguP2QapQBoIeNnHu/v/Zvi7Ivlmrh+SRbK01/nuBrsf5gUcOdp0dcvzMpqKtOV9PLVKtT5t0ywYY7gO8ZRSnnPvjHekSSMgnwwNOTok9xgkY9hCSJHEwbyquPi3jFRe7xYz6fX0Ugxk63WCu4b4Gr5BgMVk/x2jjlYzII5+BItZF8oTvUw8XgQ/9TZ0Kh0uGXy7Me4gkg8RmdMVuFxRtMq/jpxxSZNazqN6Q67UzojwcyUF6Rm/1ntFvzKOP+13mzndXsEhx9pHK5K7wHFYNGQkmgi8o/fZCHXL/QhteT+BNr3HqclbrCrdgMO+EvYPmXGasNr1Er2hmwIWceiW/fH9OBQT/r3mIuJ/o85p8yj+mbwMVD9/Oa1ViO0gLdb9VR8UNaqVW3KfJ2ZlPMt8kF3YhP2TIoRxk8ibkcozbqjslzb2g4psIf/LNM8lCQDWJ4QtNWyqmyA7QHmbuJi3pNH4TYc/xL//0V74nvV7sDjsdHARjJnSouu7B7IltmZETI4jwAhCLmJnWiuiuhHU6MIyrsKlQaCtnlvAXk/Mrvrg4PE+mZz1Ndcw="
  file: target/swagger-diff-$project_version.jar
  on:
    repo: emm035/swagger-diff
    branch: travis-publishing
    name: "$project_version"
