language: java
script: mvn clean install
before_deploy:
- gpg --import gpg.asc
- mvn help:evaluate -N -Dexpression=project.version|grep -v '\['
- export project_version=$(mvn help:evaluate -N -Dexpression=project.version|grep
  -v '\[')
- git tag -f $project_version
deploy:
  provider: releases
  api_key:
    secure: fEn2bNENXNadDFTeuvmtWcXmOihGBIpql2Y2ZiRlElUSqsf8F6c+kScjok2qtOfAT+P3sm6E8jjlo8h/EMJaoTPEw5ZGsu1I+58APvp8HOB8Iw38NQK6tRxz4ItH/Ye9bxC0/kud7j/Ctob5nQyx/7hZPjut05Re2ybsM+Tc8x0l1V94L/sNT0OCzGsrOhmTxzeLAmVB5rNpbBoi/d+97jGIGzKeuRnIFJ2pIN0E/ZGJFQU+MAkxsqb7rkwtd3apB70yCn4a7E6auvc6GQF3RWo0NY+WuYUDSlq9oGH+esezjrnMxgFwqwAt+Wj9hhcKgstLJcBYBOLxb84fY3GV7JdQzvQiLOjgGquJZ7OxdTlkR5nrfkO+3YFHzJfg8nPAycgd8v8JXP0y9MLr4EuA/DaEK7N+UtksoPFo7dqKCKm4gZWI7YfKL0KNiqZE2QuoNEJFHZ1c899H9QONXfkULmwzL8veBQL4gU6XmoUbnS7L69sIsNvwVaIJf9Mwkv9r80D1dQHzyRzbzXcGbdV8lw+vSdfCmMVfcdxFUSLQzsg4oPwc4dF1Edoi9xBEi622UNNRcLR+7egFiMcUkEN/1ovf5rf6xmnwyLHGpb1uZEExOi5di+lH3YHhKg6eMgF8TANx2bYf1So741r6VCwoXj+07F0cpUJpYdl462I0soM=
  file: target/swagger-diff-$project_version.jar
  skip_cleanup: true
  on:
    repo: emm035/swagger-diff
    branch: travis-publishing
  name: "$project_version"
after_deploy:
- mvn deploy gpg:sign --settings .travis.settings.xml -DskipTests=true -B
env:
  global:
    secure: Qtvmq5PDLH7rKWIKt4aVIV85ZKcG264jTeMjvW7t6sJUqZ1u5ySxcKiBn+8BQ8BYqNvJgdWjiBwSunyeewV2L81od86bDK7dobVYu4HCwukdJSdxsPW4+D2v0KGXmfH1i2qiNNJ/Uk4Beqq4gJtVISpVIMs3ydJnPoeLuT1V/geAj2B5SOUrW1RDlrNqQvyaS9i4PTkkt5Mjhxpi2Uxml2K1XkO6vi5lNNIJRiHnlMoa4U6su6O6fm5oWhCs0fFke8C1KGr1oFn0ogCxBNBWPgppsc+gjFGFd2EdglmdnMp73C1N359Xk21rcq5INEYkdMC6grpsnLCmzUQct42eZ85L3eN761QOc1qU6R+hGxTckILy1fyFaHD0IBNbwSebJcKys3T1+W5Dy8qay6azKFLI6A2i+dt2pLrXzuoh/E+NkwxVcxkJOl+09DRvX3tyJVOxh+ix2d5qxz6wWaZkSaEjxkpRmKS+016i2NhPSUt5r6ds+kevAaZpJnBRlw+PCnuFlURUXBq03DgYhs4+URYPnkIpSTgeZOcliHFhSbvEXRMC0E+HnGhFX6u3xIQzMEYLODg++eKgxp4XZzo2RGals1tldmkaX0oWy0gNJHu+ng97FRFcTr/Z9VVYUGHmz7NHRE/uE7F+IIV18KgFCGiOsha82SytopcXxEID5eY=
before_install:
- openssl aes-256-cbc -K $encrypted_7bd4377d7160_key -iv $encrypted_7bd4377d7160_iv
  -in gpg.asc.enc -out gpg.asc -d
