language: java
script: mvn clean install
before_deploy:
- mvn help:evaluate -N -Dexpression=project.version|grep -v '\['
- export project_version=$(mvn help:evaluate -N -Dexpression=project.version|grep
  -v '\[')
deploy:
  provider: releases
  api_key:
    secure: GP4tXwYBDDkaaU0rfHVNFy1PtU3Tod7Z6wYMGgEpLYRQCaeGJrcSO9BjVutCVB870K3jkSGU0AB1/ZHvmybXglQbv8MTaKJBbkkMUk8Gt0R9WJ+4a3gdQn9hKZLPkQqXdOTFiRom+rBzkEBnp8YF+Z17BCW5wgQJaYxecwnUruchE6BAoA1E/Mgtvkm0tvmQUB5OL54OoysHt77jauRMGMqnK0ZMp9Q/nrA9taLOYe3/4VzwLYrv9HaYDN7nNjwfEFoOYmMMG4cTBRtrhZpI2uGM7tvth1AepTJOPJY6Zd2aW3f09s3CfzTTn7iWdd37PU30V9etXYYINe+uoEsGGwuzCXiHxCigXZWydDw74kqqqUi0yw1sa79S1Jg1cyQPHY6Gvv23bjF4c736PbUHvcXgaKML97RdoSkH5+bVZcJOHHE/yl30c954ioUCuLx/wx31Q8p94Kmy6oy9mkDajdjEQieLrTHuNe90lpaxk/6nPNVq2baqLaW19S5iqluj9Gyb/477FtmRar0v/Jzqe3NOfzRGnv3lD98T8K2XbJV+s5s0PeqsmE2EPcF5iyfvW38aU0b3x/hWkTfbFS63wTYz37d0AY8y1UWrdV0Ifi8huqZva+fawspFHwmQzi7eyqOc+sdkbIiPxDJb8jfKiRuU0/Sy3NuJ7oBBRXHfnig=
  file: target/swagger-diff-$project_version.jar
  on:
    repo: emm035/swagger-diff
    branch: travis-publishing
  name: $project_version
  overwrite: true
